# Este archivo se usa principalmente para análisis local.
# Para SonarCloud, las propiedades se pasan por línea de comandos en el workflow.
sonar.projectName=Productos Service
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=*/*Application.java
# Las siguientes líneas están comentadas porque en SonarCloud se definen en el workflow
# sonar.projectKey=com.universidad:productos-service
# sonar.host.url=http://localhost:9000
# sonar.qualitygate.wait=false